### ISSUE TITLE
Update compressed film parameters

### ISSUE THREAD

**Issue by claresinger** [claresinger/PySDM-examples#3]
Hi @slayoo,

Big picture: I'm trying to do MCMC to find the optimal parameters values for the compressed film model.

Small picture: I'm trying just to make a plot where I have two curves for the surface tension given different parameter values in the compressed film framework (`delta_min` and `sgm_org`). You can see in [this notebook](https://github.com/claresinger/PySDM-examples/blob/cf_ruehl/PySDM_examples/Singer/surf_tens_mcmc.ipynb) that I update the parameters, but the returned surface tension is unchanged. Specifically I have narrowed it down to this:

```
compressed_film_Ovadnevaite.sgm_org = 40.1 * si.mN / si.m
compressed_film_Ovadnevaite.delta_min = 0.30 * si.nm
formulae_1 = Formulae(surface_tension='CompressedFilm_Ovadnevaite')

compressed_film_Ovadnevaite.sgm_org = 28.5 * si.mN / si.m
compressed_film_Ovadnevaite.delta_min =  0.52 * si.nm
formulae_2 = Formulae(surface_tension='CompressedFilm_Ovadnevaite')

print(formulae_1 == formulae_2)
print(formulae_1.surface_tension == formulae_2.surface_tension)
print(formulae_1.surface_tension.sigma == formulae_2.surface_tension.sigma)
```
>False
>True
>True

So the `formulae` are updating, but the `formulae.surface_tension` are not. How can I get around this? Thanks so much for your help!

**Comment by slayoo** [comment]
Good question! And this is the same as issue https://github.com/atmos-cloud-sim-uj/PySDM/issues/634
Numba treats globals as constants and does not track further changes made to these values, so anything compiled before a change to a global value maintains the old value. The intention was for the Formulae instantiation to trigger compilation of all the underlying formulae, but apparently, some caching is happening... I'm trying to debug it...

**Comment by slayoo** [comment]
In the meantime, you can switch Numba off completely by setting  NUMBA_DISABLE_JIT=1 (env var)

**Comment by claresinger** [comment]
Fantastic! Thanks @slayoo! It works now :) 

https://github.com/claresinger/PySDM-examples/blob/cf_ruehl/PySDM_examples/Singer/surf_tens_mcmc.ipynb

**Comment by slayoo** [comment]
The constants settings logic needs a rewrite... whatever workaround we will come up for the above problem, it will anyhow not work with the GPU backend... :(

**Comment by claresinger** [comment]
@slayoo This issue is now fixed as you wrote [here](https://github.com/atmos-cloud-sim-uj/PySDM-examples/pull/68#issuecomment-1003977128), correct?

**Comment by slayoo** [comment]
Yes! (and it does work with GPU backend as well)
